version: '3'
services: 
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
  redis: 
    image: 'redis:latest'
  nginx:
    restart: always
    build:  
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:  
      - '3050:80'
  api:
    build: 
      dockerfile: 'Dockerfile.dev'
      context: ./server
    volumes:
    # don't overwrite this folder
      - /app/node_modules
    # copy everything inside the SERVER folder to APP folder of the container
      - ./server:/app
    environment:
      - WDS_SOCKET_PORT=0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      # everything inside the Client folder shold be share in the APP folder
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  
